"""initial database

Revision ID: e336a6cbad45
Revises: 
Create Date: 2026-01-25 15:53:44.171023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e336a6cbad45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrevistados',
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('email_corporativo', sa.String(length=150), nullable=False),
    sa.Column('genero', sa.String(length=15), nullable=False),
    sa.Column('geracao', sa.String(length=15), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('funcao', sa.String(length=50), nullable=False),
    sa.Column('localidade', sa.String(length=50), nullable=False),
    sa.Column('tempo_empresa', sa.String(length=50), nullable=False),
    sa.Column('n0_empresa', sa.String(length=50), nullable=False),
    sa.Column('n1_diretoria', sa.String(length=50), nullable=False),
    sa.Column('n2_gerencia', sa.String(length=50), nullable=False),
    sa.Column('n3_coordenacao', sa.String(length=50), nullable=False),
    sa.Column('n4_area', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perguntas',
    sa.Column('pergunta', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas',
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nota', sa.SmallInteger(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('pergunta_fk', sa.Integer(), nullable=False),
    sa.Column('entrevistado_fk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entrevistado_fk'], ['entrevistados.id'], ),
    sa.ForeignKeyConstraint(['pergunta_fk'], ['perguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respostas_data'), 'respostas', ['data'], unique=False)
    op.create_index(op.f('ix_respostas_entrevistado_fk'), 'respostas', ['entrevistado_fk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respostas_entrevistado_fk'), table_name='respostas')
    op.drop_index(op.f('ix_respostas_data'), table_name='respostas')
    op.drop_table('respostas')
    op.drop_table('perguntas')
    op.drop_table('entrevistados')
    # ### end Alembic commands ###
