"""Add response index

Revision ID: fbf74856f1ab
Revises: 8de5ccd4aa1a
Create Date: 2026-01-24 23:59:29.709801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf74856f1ab'
down_revision: Union[str, Sequence[str], None] = '8de5ccd4aa1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_respostas_data'), 'respostas', ['data'], unique=False)
    op.create_index(op.f('ix_respostas_entrevistado_fk'), 'respostas', ['entrevistado_fk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respostas_entrevistado_fk'), table_name='respostas')
    op.drop_index(op.f('ix_respostas_data'), table_name='respostas')
    # ### end Alembic commands ###
